---
services:
  db:
    container_name: vdb
    image: pgvector/pgvector:pg18-trixie
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ishi
    volumes:
    - pgv:/var/lib/postgresql
    ports:
    - 5432:5432
    models:
    - embedding-model

models:
  embedding-model:
    model: ai/nomic-embed-text-v1.5

volumes:
  pgv:
