---
services:
  db:
    container_name: vdb
    image: pgvector/pgvector:pg18-trixie
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ishi
    volumes:
    - pgv:/var/lib/postgresql
    ports:
    - 5432:5432

  ollama:
    container_name: ollama
    image: ollama/ollama
    volumes:
    - ollama:/root/.ollama
    ports:
    - 11434:11434

volumes:
  ollama:
  pgv:
